<a href="https://colab.research.google.com/github/samibahig/PersonnalExercices/blob/main/ExerciceTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np
import matplotlib as plt
X = torch.Tensor([[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]])
y = X.diag()
y

tensor([ 0.,  5., 10.])

In [ ]:
x = torch.arange(2, 101, 2)
print(x)

tensor([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,  28,
         30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,  54,  56,
         58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,  80,  82,  84,
         86,  88,  90,  92,  94,  96,  98, 100])


In [ ]:
x = torch.logspace(3, 10, 50)

assert np.allclose(x.numpy(), np.logspace(3., 10., 50))

plt.figure()
plt.scatter(range(len(_x)), _x)
plt.show()

TypeError: ignored

In [ ]:
X = torch.Tensor([[ 0, 1, 2, 3], [ 4, 5, 6, 7], [ 8, 9, 10, 11]])
y = X.diag()
print(y)

tensor([ 0.,  5., 10.])


In [ ]:
X = torch.Tensor([[ 0, 1, 2, 3], [ 4, 5, 6, 7], [ 8, 9, 10, 11]])
y = X.diag(1)
print(y)

tensor([ 1.,  6., 11.])


In [ ]:
X = torch.Tensor([[ 0, 1, 2, 3], [ 4, 5, 6, 7], [ 8, 9, 10, 11]])
y = X.trace()
print(y)

tensor(15.)


In [ ]:
X = torch.Tensor([[1,2,3], [4,5,6], [7,8,9]])
Y = X.tril()
print(Y)

tensor([[1., 0., 0.],
        [4., 5., 0.],
        [7., 8., 9.]])


In [ ]:
X = torch.randn(3,2,1)
X

tensor([[[ 0.5994],
         [-1.6945]],

        [[-1.0224],
         [-0.3260]],

        [[ 1.1086],
         [ 0.6237]]])

In [ ]:
X = torch.randn(3,2,1)
Y = X.tolist()
print(type(Y))

<class 'list'>


In [ ]:
X = torch.IntTensor(3, 2).fill_(0)
print("X=>", X.type())
Y = X.float()
print("Y=>", Y.type())

X=> torch.IntTensor
Y=> torch.FloatTensor


In [ ]:
X = torch.randn(3, 2, 1)
y = X.numel()
print(y)

6


In [ ]:
X = torch.ones(5, 6)
Y = X.resize_(10, 3)
print(Y.size())

torch.Size([10, 3])


In [ ]:
X = torch.randn(10, 10, 1, 1)
Y = X.squeeze()
print(Y.size())

torch.Size([10, 10])


In [ ]:
X = torch.randn(10, 10)
X.squeeze(1)

tensor([[-0.7415, -0.7136,  0.2661, -0.4028,  0.7970, -0.0539, -1.1345, -0.2831,
          1.8938,  0.4219],
        [-0.6582,  1.2510,  1.3419, -0.9179, -0.2713,  0.7518,  0.5491,  0.3698,
          0.4266, -1.2393],
        [ 0.5016,  0.3209,  0.9802,  0.0636, -0.9834,  2.8208, -0.3393, -1.5388,
         -0.7028,  1.1137],
        [ 1.7586, -1.4046,  0.1522,  0.8378,  0.1675, -0.4099, -0.7225, -1.7369,
         -0.4955,  1.1824],
        [ 0.5972, -0.1215,  0.9578, -0.0462,  1.0047,  0.5613,  0.6294, -0.2821,
          0.9823,  0.8531],
        [ 0.2916,  0.0629, -0.9459, -0.2506, -2.3167,  1.0702,  0.4126, -0.4645,
         -0.2646,  0.8642],
        [ 0.4497, -1.3726, -0.9103, -1.2490, -1.2118,  1.1322, -0.7800,  0.0947,
          0.4693, -0.0182],
        [-0.6920,  1.2356,  0.3224, -0.2008, -0.0300, -1.5233, -0.6421,  0.9090,
          1.0591,  0.7013],
        [ 0.0320, -2.2665, -0.1210,  1.0518,  1.2405,  0.4436, -0.2578, -0.2919,
         -0.7511, -1.3566],
        [ 0.3754, -

In [ ]:
x = torch.arange(1, 11)
x
mask = x.gt(5)
x, mask
print("masked=", x.masked_select(mask))

masked= tensor([ 6,  7,  8,  9, 10])
