<a href="https://colab.research.google.com/github/samibahig/PersonnalExercices/blob/main/ExerciceTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np

In [ ]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

In [ ]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [ ]:
x_ones = torch.ones_like(x_data)

In [ ]:
tensor = torch.rand(3,4)

In [ ]:
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32


In [ ]:
if torch.cuda.is_available():
    tensor = tensor.to('cuda')

In [ ]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [ ]:
x_ones = torch.ones_like(x_data)
print(f"Ones Tensor:\n {x_ones} \n")

Ones Tensor:
 tensor([[1, 1],
        [1, 1]]) 



In [ ]:
x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f'Random Tensor')

In [ ]:
tensor = torch.rand(3, 4)

In [ ]:
if torch.cuda.is_available():
    tensor = tensor.to('cuda')

In [ ]:
tensor = torch.ones(4, 4)
tensor[:,1] = 0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [ ]:
t = torch.ones(5)
print(f'f: {t}')

f: tensor([1., 1., 1., 1., 1.])


In [ ]:
n = t.numpy()
print(f"n: {n}")

n: [1. 1. 1. 1. 1.]


In [ ]:
t.add_(1)
print(f"t: {t}")

t: tensor([2., 2., 2., 2., 2.])


In [ ]:
n = np.ones(5)
t = torch.from_numpy(n)

In [ ]:
np.add(n, 1, out=n)
print(f't: {t}')

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [ ]:
tensor = torch.rand(3, 4)

In [ ]:
if torch.cuda.is_available():
    tensor = tensor.to('cuda')

In [ ]:
tensor = torch.ones(4, 4)

In [ ]:
tensor[:, 1] = 0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [ ]:
if torch.cuda.is_available():
    tensor = tensor.to('cuda')

In [ ]:
tensor = torch.ones(4, 4)
tensor[:, 1] = 0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [ ]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [ ]:
tensor.add_(5)
print(tensor)

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


In [ ]:
t = torch.ones(5)

In [ ]:
t.add_(1)

tensor([2., 2., 2., 2., 2.])

In [ ]:
n = np.ones(5)
t = torch.from_numpy(n)

In [ ]:
x = torch.tensor(1., requires_grad=True)
w = torch.tensor(2., requires_grad=True)
b = torch.tensor(3., requires_grad=True)

In [ ]:
x = torch.randn(10, 3)
y = torch.randn(10, 2)

In [ ]:
x, y

(tensor([[-0.8633, -1.0731,  0.0124],
         [ 0.2209,  0.3464,  0.8692],
         [-1.5317, -0.8365,  0.6625],
         [-0.7612,  0.8180,  0.7100],
         [-0.2411,  0.6376, -0.1560],
         [ 1.4960, -1.2911, -0.3156],
         [ 0.2125,  0.3871, -0.0388],
         [ 0.1379,  0.7975, -0.6446],
         [ 0.3116,  0.3702, -0.7255],
         [ 1.3647, -1.6561,  1.0449]]), tensor([[-1.0883, -0.3975],
         [ 0.1991, -0.9161],
         [ 0.1879, -0.8616],
         [ 0.2839,  1.1130],
         [ 1.0935,  1.3184],
         [-0.1574, -0.4453],
         [ 0.6436,  1.7667],
         [-0.2754, -0.6340],
         [ 1.0468, -0.4652],
         [ 0.3038,  0.3039]]))

In [ ]:
import torch.nn as nn
criterion = nn.MSELoss()

In [ ]:
linear = nn.Linear(3, 2)

In [ ]:
print('w: ', linear.weight)
print('b: ', linear.bias)

w:  Parameter containing:
tensor([[ 0.3677, -0.2814,  0.4147],
        [-0.4018,  0.2355,  0.1583]], requires_grad=True)
b:  Parameter containing:
tensor([0.2653, 0.4517], requires_grad=True)


In [ ]:
loss = criterion(pred, y)
print('loss: ', loss.item())

NameError: ignored

In [ ]:
loss.backward()

NameError: ignored

In [ ]:
custom_dataset = CustomDataset()
train_loader = torch.utils.data.DataLoader(dataset=custom_dataset, batch_size=64, shuffle=True)

NameError: ignored

In [ ]:
x = torch.tensor(1., requires_grad=True)

In [ ]:
custom_dataset = CustomDataset()
train_loader = torch.utils.data.DataLoader(dataset=custom_dataset, batch_size=64, shuffle=True)

NameError: ignored

In [ ]:
class NeuralNet(nn.Module):
    def __init__(self, input_size, hidden_size, num_classes):
        super(NeuralNet, self).__init__()
        self.fc1 = nn.Linear(input_size, hidden_size) 
        self.relu = nn.ReLU()
        self.fc2 = nn.Linear(hidden_size, num_classes)  
    
    def forward(self, x):
        out = self.fc1(x)
        out = self.relu(out)
        out = self.fc2(out)
        return out

In [ ]:
total_step = len(train_loader)
for epoch in range(num_epochs):
    for i, (images, labels) in enumerate(train_loader): 
        images = images.reshape(-1, 28*28).to(device)
        labels = labels.to(device)

NameError: ignored

In [ ]:
with torch_grad():
    correct = 0
    total = 0
    for images, labels in test_loader:
        images = images.reshape(-1, 28*28).to(device)
        labels = labels.to(device)
        outputs = model(images)
        _, predicted = torch.max(outputs.data, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

NameError: ignored

In [ ]:
import torch 
import torch.nn as nn
import torchvision.transforms as transforms