<a href="https://colab.research.google.com/github/samibahig/PersonnalExercices/blob/main/ExerciceNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
list_of_list = [['Paris', 75], ['Lyon', 69]]

In [ ]:
list = [1, 'film', 3]

In [ ]:
list.append('series')
print(list)

[1, 'film', 3, 'series']


In [ ]:
import numpy as np

In [ ]:
vector = np.array([3, 4, 17, 65])

In [ ]:
matrix = np.array([[2, 5, 15], [20, 50, 30], [34, 99, 45]])

In [ ]:
print(matrix)

[[ 2  5 15]
 [20 50 30]
 [34 99 45]]


In [ ]:
import numpy as np
vector = np.array([10, 20, 30])
matrix = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])
print(vector)

[10 20 30]


In [ ]:
vector = np.array([1, 2, 3, 4])
print(vector.shape)

(4,)


In [ ]:
matrix = np.array([[5, 10, 15], [20, 25, 30]])
print(matrix.shape)

(2, 3)


In [ ]:
vector_shape = vector.shape
matrix_shape = matrix.shape
print(vector_shape)
print(matrix_shape)

(4,)
(2, 3)


In [ ]:
import numpy as np
test = np.genfromtxt('data.csv', delimiter=',')

In [ ]:
import pandas as pd
reviews = pd.read_csv('fandango_scores.csv')
cols = ['FILM', 'RT_user_norm', 'Metacritic_user_nom', 'IMDB_norm', 'Fandango_Ratingvalue']

norm_reviews = reviews[cols]
print(norm_reviews[:5])

FileNotFoundError: ignored

In [ ]:
sorted_freq_counts = freq_counts.sort_index()
sorted_freq_counts

NameError: ignored

In [ ]:
imdb_distribution = norm_reviews['IMDB_norm'].value

NameError: ignored

In [ ]:
imdb_distribution = imdb_distribution.sort_index()

NameError: ignored

In [ ]:
import matplotlib.pyplot a splt
fig, ax = plt.subplots()
ax.hist(norm_reviews['Fandango_Ratingvalue'], range=(0,5))

SyntaxError: ignored

In [ ]:
ax.hist(df[col], range=(0,5))

NameError: ignored

In [ ]:
import matplotlib.pyplot as plt 
fig = plt.figure(figsize=(5,20))

<Figure size 360x1440 with 0 Axes>