<a href="https://colab.research.google.com/github/samibahig/PersonnalExercices/blob/main/torch_Exercice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from __future__ import print_function
import torch
import numpy as np
import matplotlib
%matplotlib inline
import matplotlib.pyplot as plt

In [ ]:
from datetime import date
date.today()

datetime.date(2021, 1, 29)

In [ ]:
author = "kyubyong. https://github.com/Kyubyong/pytorch_exercises"

In [ ]:
torch.__version__

'1.7.0+cu101'

In [ ]:

np.__version__

'1.19.5'

In [ ]:
a = [[1, 2, 3], [4, 5, 6]]
X = torch.IntTensor(a)
print(X)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)


In [ ]:
X = torch.FloatTensor(3,2).fill_(10)
print(X)

tensor([[10., 10.],
        [10., 10.],
        [10., 10.]])


In [ ]:
_x = np.array([1, 2, 3])
x = torch.from_numpy(_x)
print(x)

tensor([1, 2, 3])


In [ ]:
X = torch.eye(3)
print(X) 

assert np.array_equal(X.numpy(), np.eye(3))

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [ ]:
X = torch.zeros(3, 2)
print(X)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


In [ ]:
X = torch.arange(2, 101, 2)
print(X)

tensor([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,  28,
         30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,  54,  56,
         58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,  80,  82,  84,
         86,  88,  90,  92,  94,  96,  98, 100])


In [ ]:
x = torch.linspace(3, 10, 50)
print(x)

tensor([ 3.0000,  3.1429,  3.2857,  3.4286,  3.5714,  3.7143,  3.8571,  4.0000,
         4.1429,  4.2857,  4.4286,  4.5714,  4.7143,  4.8571,  5.0000,  5.1429,
         5.2857,  5.4286,  5.5714,  5.7143,  5.8571,  6.0000,  6.1429,  6.2857,
         6.4286,  6.5714,  6.7143,  6.8571,  7.0000,  7.1429,  7.2857,  7.4286,
         7.5714,  7.7143,  7.8571,  8.0000,  8.1429,  8.2857,  8.4286,  8.5714,
         8.7143,  8.8571,  9.0000,  9.1429,  9.2857,  9.4286,  9.5714,  9.7143,
         9.8571, 10.0000])


In [ ]:
torch.arange(2, 101, 2)

tensor([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,  28,
         30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,  54,  56,
         58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,  80,  82,  84,
         86,  88,  90,  92,  94,  96,  98, 100])

In [ ]:
torch.linspace(3, 10, 50)

tensor([ 3.0000,  3.1429,  3.2857,  3.4286,  3.5714,  3.7143,  3.8571,  4.0000,
         4.1429,  4.2857,  4.4286,  4.5714,  4.7143,  4.8571,  5.0000,  5.1429,
         5.2857,  5.4286,  5.5714,  5.7143,  5.8571,  6.0000,  6.1429,  6.2857,
         6.4286,  6.5714,  6.7143,  6.8571,  7.0000,  7.1429,  7.2857,  7.4286,
         7.5714,  7.7143,  7.8571,  8.0000,  8.1429,  8.2857,  8.4286,  8.5714,
         8.7143,  8.8571,  9.0000,  9.1429,  9.2857,  9.4286,  9.5714,  9.7143,
         9.8571, 10.0000])

In [ ]:
torch.logspace(3, 10, 50)

tensor([1.0000e+03, 1.3895e+03, 1.9307e+03, 2.6827e+03, 3.7276e+03, 5.1795e+03,
        7.1969e+03, 1.0000e+04, 1.3895e+04, 1.9307e+04, 2.6827e+04, 3.7276e+04,
        5.1795e+04, 7.1969e+04, 1.0000e+05, 1.3895e+05, 1.9307e+05, 2.6827e+05,
        3.7276e+05, 5.1795e+05, 7.1969e+05, 1.0000e+06, 1.3895e+06, 1.9307e+06,
        2.6827e+06, 3.7276e+06, 5.1795e+06, 7.1969e+06, 1.0000e+07, 1.3895e+07,
        1.9307e+07, 2.6827e+07, 3.7276e+07, 5.1795e+07, 7.1969e+07, 1.0000e+08,
        1.3895e+08, 1.9307e+08, 2.6827e+08, 3.7276e+08, 5.1795e+08, 7.1969e+08,
        1.0000e+09, 1.3895e+09, 1.9307e+09, 2.6827e+09, 3.7276e+09, 5.1795e+09,
        7.1969e+09, 1.0000e+10])

In [ ]:
X = torch.Tensor([[ 0, 1, 2, 3], [ 4, 5, 6, 7], [ 8, 9, 10, 11]])
y = X.diag()
print(y)

tensor([ 0.,  5., 10.])


In [ ]:
assert np.array_equal(y.numpy(), np.diag(X.numpy()))

In [ ]:
X = torch.Tensor([[ 0, 1, 2, 3], [ 4, 5, 6, 7], [ 8, 9, 10, 11]])
X
#y = X.diag(3)
#print(y)

#assert np.array_equal(y.numpy(), np.diag(X.numpy(), 1))

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])